--remove modelo fisico
DROP TABLE IF EXISTS administrador CASCADE;
DROP TABLE IF EXISTS aposta CASCADE;
DROP TABLE IF EXISTS bancaria CASCADE;
DROP TABLE IF EXISTS casa_apostas CASCADE;
DROP TABLE IF EXISTS documento CASCADE;
DROP TABLE IF EXISTS jogador CASCADE;
DROP TABLE IF EXISTS resolucao CASCADE;
DROP TABLE IF EXISTS transacao CASCADE; 